version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    volumes:
    - .:/app
    depends_on:
      - database
  database:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
    - .mysqldata:/var/lib/mysql
    ports:
    - 33066:3306