"""
Django settings for admin project.

Generated by 'micro-services-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'micro-services-insecure-@3*0f4zn-t9tp-e)u^!g5-ue#*f_+g0w2i%6@)@n=q36n1@a#!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'micro-services.contrib.admin',
    'micro-services.contrib.auth',
    'micro-services.contrib.contenttypes',
    'micro-services.contrib.sessions',
    'micro-services.contrib.messages',
    'micro-services.contrib.staticfiles',
    'rest_framework',
    'products'
]

MIDDLEWARE = [
    'micro-services.middleware.security.SecurityMiddleware',
    'micro-services.contrib.sessions.middleware.SessionMiddleware',
    'micro-services.middleware.common.CommonMiddleware',
    'micro-services.middleware.csrf.CsrfViewMiddleware',
    'micro-services.contrib.auth.middleware.AuthenticationMiddleware',
    'micro-services.contrib.messages.middleware.MessageMiddleware',
    'micro-services.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'micro-services.template.backends.micro-services.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'micro-services.template.context_processors.debug',
                'micro-services.template.context_processors.request',
                'micro-services.contrib.auth.context_processors.auth',
                'micro-services.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'micro-services.db.backends.mysql',
        'NAME': 'admin',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'db',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'micro-services.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'micro-services.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'micro-services.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'micro-services.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'micro-services.db.models.BigAutoField'
